#!/usr/bin/env python3
"""
gen_routes_trips.py — seed routes + trips so every scraped shape is reachable.

`/route/shape` joins trips -> route_shapes, so a shape only renders if a trip
links route_<code> to shape_<code>. This reads the already-downloaded KMZs in
data/routes/ (no network) and emits a migration that:

  * upserts the agency used by the seed (CCT)
  * inserts a routes row per code (ON CONFLICT DO NOTHING — existing routes like
    13C/04L keep their hand-tuned metadata)
  * inserts a trips row per code with shape_id = shape_<code> pre-linked

Route long names come from the primary (longest) direction in each KMZ.

Usage:
    python gen_routes_trips.py \
        --out sugboway-routing-api/adapter/repository/migrations/0004_weebly_routes_trips.sql
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from parse_kmz import routes_from_kml, _read_kml_text

DATA_DIR = Path("data/routes")


def _sql_str(s: str) -> str:
    """Single-quote-escape for SQL string literals."""
    return s.replace("'", "''")


def primary_name(kmz_path: Path) -> str | None:
    lines = list(routes_from_kml(_read_kml_text(str(kmz_path))))
    if not lines:
        return None
    lines.sort(key=lambda nc: len(nc[1]), reverse=True)
    name = lines[0][0].strip()
    return name or None


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate routes/trips seed for scraped shapes")
    ap.add_argument("--out", help="Write SQL here (default: stdout)")
    args = ap.parse_args()

    kmz_files = sorted(DATA_DIR.glob("*.kmz"))
    if not kmz_files:
        print("error: no KMZs in data/routes/ — run scrape_weebly_routes.py first", file=sys.stderr)
        return 2

    out: list[str] = []
    out.append("-- ======================================================================")
    out.append("-- 0004_weebly_routes_trips.sql — make every scraped shape reachable")
    out.append("-- ======================================================================")
    out.append("-- Generated by gen_routes_trips.py from data/routes/*.kmz.")
    out.append("-- Geometry/names: cebujeepneys.weebly.com (CC BY-NC 3.0). See SOURCES.md.")
    out.append("--")
    out.append("-- /route/shape needs trips.route_id + trips.shape_id, so we add a routes")
    out.append("-- row and a trip (shape_id pre-linked) for each scraped code. Existing")
    out.append("-- routes keep their metadata (ON CONFLICT DO NOTHING).")
    out.append("")
    out.append("-- Agency used by the seed (no-op if it already exists).")
    out.append("INSERT INTO agency (agency_id, agency_name, agency_timezone) VALUES")
    out.append("    ('CCT', 'Cebu City Transit', 'Asia/Manila')")
    out.append("ON CONFLICT (agency_id) DO NOTHING;")
    out.append("")

    route_rows: list[str] = []
    trip_rows: list[str] = []
    count = 0
    skipped: list[str] = []

    for kmz in kmz_files:
        code = kmz.stem.lower()
        name = primary_name(kmz)
        if not name:
            skipped.append(code)
            continue
        count += 1
        route_id = f"route_{code}"
        shape_id = f"shape_{code}"
        trip_id = f"trip_{code}"
        short = code.upper()
        long_name = _sql_str(name)
        route_rows.append(
            f"    ('{route_id}', 'CCT', '{short}', '{long_name}', 3)"
        )
        trip_rows.append(
            f"    ('{trip_id}', '{route_id}', 'all_days', '{shape_id}')"
        )

    out.append(f"-- {count} routes")
    out.append("INSERT INTO routes (route_id, agency_id, route_short_name, route_long_name, route_type) VALUES")
    out.append(",\n".join(route_rows))
    out.append("ON CONFLICT (route_id) DO NOTHING;")
    out.append("")
    out.append("INSERT INTO trips (trip_id, route_id, service_id, shape_id) VALUES")
    out.append(",\n".join(trip_rows))
    out.append("ON CONFLICT (trip_id) DO NOTHING;")
    out.append("")
    # Belt-and-suspenders: link any pre-existing trip that still lacks a shape.
    out.append("-- Link any existing trip that has no shape yet to its matching shape.")
    out.append("UPDATE trips t SET shape_id = 'shape_' || split_part(t.route_id, '_', 2)")
    out.append("WHERE t.shape_id IS NULL")
    out.append("  AND EXISTS (SELECT 1 FROM route_shapes rs")
    out.append("             WHERE rs.shape_id = 'shape_' || split_part(t.route_id, '_', 2));")
    out.append("")

    sql = "\n".join(out)
    if args.out:
        Path(args.out).write_text(sql, encoding="utf-8")
        print(f"Wrote {count} routes/trips to {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(sql)
    if skipped:
        print(f"skipped (no geometry): {', '.join(skipped)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
