-- ======================================================================
-- 0004_weebly_routes_trips.sql — make every scraped shape reachable
-- ======================================================================
-- Generated by gen_routes_trips.py from data/routes/*.kmz.
-- Geometry/names: cebujeepneys.weebly.com (CC BY-NC 3.0). See SOURCES.md.
--
-- /route/shape needs trips.route_id + trips.shape_id, so we add a routes
-- row and a trip (shape_id pre-linked) for each scraped code. Existing
-- routes keep their metadata (ON CONFLICT DO NOTHING).

-- Agency used by the seed (no-op if it already exists).
INSERT INTO agency (agency_id, agency_name, agency_timezone) VALUES
    ('CCT', 'Cebu City Transit', 'Asia/Manila')
ON CONFLICT (agency_id) DO NOTHING;

-- 54 routes
INSERT INTO routes (route_id, agency_id, route_short_name, route_long_name, route_type) VALUES
    ('route_01b', 'CCT', '01B', 'Sambag 1 to Pier 3 & 2 via Colon St', 3),
    ('route_01c', 'CCT', '01C', 'Sambag 1 to Pier 3', 3),
    ('route_01k', 'CCT', '01K', 'Urgello st. - Parkmall', 3),
    ('route_02b', 'CCT', '02B', 'Pier to Cebu South Bus Terminal', 3),
    ('route_03a', 'CCT', '03A', 'Panagdait ( Mabolo) - Carbon', 3),
    ('route_03b', 'CCT', '03B', 'Mabolo to colon via Jones ave.', 3),
    ('route_03l', 'CCT', '03L', 'Carbon - Mabolo(Luyo)', 3),
    ('route_03q', 'CCT', '03Q', 'Line 6', 3),
    ('route_04b', 'CCT', '04B', 'Carbon to Lahug', 3),
    ('route_04c', 'CCT', '04C', 'LAHUG TO CARBON', 3),
    ('route_04d', 'CCT', '04D', 'Carbon to Plaza Housing (Busay)', 3),
    ('route_04h', 'CCT', '04H', 'Plaza Housing to Carbon', 3),
    ('route_04i', 'CCT', '04I', 'Carbon to Busay(plaza housing)', 3),
    ('route_04l', 'CCT', '04L', 'Lahug to SM via Ayala', 3),
    ('route_04m', 'CCT', '04M', 'Jy Square (Lahug) to Ayala Terminal', 3),
    ('route_06b', 'CCT', '06B', 'Basilica del Snto. Nino - Guadalupe', 3),
    ('route_06c', 'CCT', '06C', 'Colon to Guadalupe', 3),
    ('route_06g', 'CCT', '06G', 'C. Padilla St. to Guadalupe', 3),
    ('route_06h', 'CCT', '06H', 'from sm terminal to guadalupe church', 3),
    ('route_07b', 'CCT', '07B', 'Carbon to Banawa via Capitaol', 3),
    ('route_08g', 'CCT', '08G', 'Colon to Alumnos', 3),
    ('route_09c', 'CCT', '09C', 'Cebu Jeepney Route no. 09C', 3),
    ('route_09f', 'CCT', '09F', 'Basak-Ibabao (Quiot) to Colon', 3),
    ('route_09g', 'CCT', '09G', 'Basak (Ibabao) to Magalllanes', 3),
    ('route_10f', 'CCT', '10F', 'Junquera St. - Bulacao', 3),
    ('route_10g', 'CCT', '10G', 'Pardo to Magallanes (santo Nino)', 3),
    ('route_10h', 'CCT', '10H', '10H route bulacao  - SM', 3),
    ('route_10m', 'CCT', '10M', 'Bulacao to SM', 3),
    ('route_11a', 'CCT', '11A', 'Inayawan to Colon', 3),
    ('route_12d', 'CCT', '12D', 'Labangon to Colon', 3),
    ('route_12g', 'CCT', '12G', 'Labangon to Sm City Cebu', 3),
    ('route_12i', 'CCT', '12I', 'SM to Labangon (Tres)', 3),
    ('route_12l', 'CCT', '12L', 'Labangon - Ayala Center Cebu Terminal', 3),
    ('route_13b', 'CCT', '13B', 'Carbon to Talamban via Ramos', 3),
    ('route_13c', 'CCT', '13C', 'Talamban to Colon', 3),
    ('route_13h', 'CCT', '13H', 'Mandaue Public Market to Pit-os', 3),
    ('route_14d', 'CCT', '14D', 'Ayala Terminal to Colon', 3),
    ('route_17b', 'CCT', '17B', 'Carbon To Apas', 3),
    ('route_17c', 'CCT', '17C', 'Carbon to Apas', 3),
    ('route_17d', 'CCT', '17D', 'Carbon to Apas', 3),
    ('route_20a', 'CCT', '20A', 'ayala to mandaue (mercado - parkmall)', 3),
    ('route_20b', 'CCT', '20B', 'ibabao (estancia) to ayala terminal', 3),
    ('route_21a', 'CCT', '21A', 'Cathedral to Pacific Mall ( Super Metro Mandaue)', 3),
    ('route_21d', 'CCT', '21D', 'Cathedral to ibabao (estancia) , super metro mandaue.', 3),
    ('route_22a', 'CCT', '22A', 'Cathedral to Ouano (Mandaue)', 3),
    ('route_22d', 'CCT', '22D', 'Cathedral to Ouano (mandaue)', 3),
    ('route_22g', 'CCT', '22G', 'Mandaue(Ouano) to Cathedral', 3),
    ('route_22i', 'CCT', '22I', 'Mandaue Public Market to Country Mall', 3),
    ('route_23', 'CCT', '23', 'Punta Engano to Parkmall', 3),
    ('route_23d', 'CCT', '23D', 'Mandaue to Opon', 3),
    ('route_24', 'CCT', '24', 'White Gold to Consolacion', 3),
    ('route_25', 'CCT', '25', 'White Gold to Liloan via J Mall', 3),
    ('route_62b', 'CCT', '62B', 'Carbon to Pit-os', 3),
    ('route_62c', 'CCT', '62C', 'Pit-os to Carbon', 3)
ON CONFLICT (route_id) DO NOTHING;

INSERT INTO trips (trip_id, route_id, service_id, shape_id) VALUES
    ('trip_01b', 'route_01b', 'all_days', 'shape_01b'),
    ('trip_01c', 'route_01c', 'all_days', 'shape_01c'),
    ('trip_01k', 'route_01k', 'all_days', 'shape_01k'),
    ('trip_02b', 'route_02b', 'all_days', 'shape_02b'),
    ('trip_03a', 'route_03a', 'all_days', 'shape_03a'),
    ('trip_03b', 'route_03b', 'all_days', 'shape_03b'),
    ('trip_03l', 'route_03l', 'all_days', 'shape_03l'),
    ('trip_03q', 'route_03q', 'all_days', 'shape_03q'),
    ('trip_04b', 'route_04b', 'all_days', 'shape_04b'),
    ('trip_04c', 'route_04c', 'all_days', 'shape_04c'),
    ('trip_04d', 'route_04d', 'all_days', 'shape_04d'),
    ('trip_04h', 'route_04h', 'all_days', 'shape_04h'),
    ('trip_04i', 'route_04i', 'all_days', 'shape_04i'),
    ('trip_04l', 'route_04l', 'all_days', 'shape_04l'),
    ('trip_04m', 'route_04m', 'all_days', 'shape_04m'),
    ('trip_06b', 'route_06b', 'all_days', 'shape_06b'),
    ('trip_06c', 'route_06c', 'all_days', 'shape_06c'),
    ('trip_06g', 'route_06g', 'all_days', 'shape_06g'),
    ('trip_06h', 'route_06h', 'all_days', 'shape_06h'),
    ('trip_07b', 'route_07b', 'all_days', 'shape_07b'),
    ('trip_08g', 'route_08g', 'all_days', 'shape_08g'),
    ('trip_09c', 'route_09c', 'all_days', 'shape_09c'),
    ('trip_09f', 'route_09f', 'all_days', 'shape_09f'),
    ('trip_09g', 'route_09g', 'all_days', 'shape_09g'),
    ('trip_10f', 'route_10f', 'all_days', 'shape_10f'),
    ('trip_10g', 'route_10g', 'all_days', 'shape_10g'),
    ('trip_10h', 'route_10h', 'all_days', 'shape_10h'),
    ('trip_10m', 'route_10m', 'all_days', 'shape_10m'),
    ('trip_11a', 'route_11a', 'all_days', 'shape_11a'),
    ('trip_12d', 'route_12d', 'all_days', 'shape_12d'),
    ('trip_12g', 'route_12g', 'all_days', 'shape_12g'),
    ('trip_12i', 'route_12i', 'all_days', 'shape_12i'),
    ('trip_12l', 'route_12l', 'all_days', 'shape_12l'),
    ('trip_13b', 'route_13b', 'all_days', 'shape_13b'),
    ('trip_13c', 'route_13c', 'all_days', 'shape_13c'),
    ('trip_13h', 'route_13h', 'all_days', 'shape_13h'),
    ('trip_14d', 'route_14d', 'all_days', 'shape_14d'),
    ('trip_17b', 'route_17b', 'all_days', 'shape_17b'),
    ('trip_17c', 'route_17c', 'all_days', 'shape_17c'),
    ('trip_17d', 'route_17d', 'all_days', 'shape_17d'),
    ('trip_20a', 'route_20a', 'all_days', 'shape_20a'),
    ('trip_20b', 'route_20b', 'all_days', 'shape_20b'),
    ('trip_21a', 'route_21a', 'all_days', 'shape_21a'),
    ('trip_21d', 'route_21d', 'all_days', 'shape_21d'),
    ('trip_22a', 'route_22a', 'all_days', 'shape_22a'),
    ('trip_22d', 'route_22d', 'all_days', 'shape_22d'),
    ('trip_22g', 'route_22g', 'all_days', 'shape_22g'),
    ('trip_22i', 'route_22i', 'all_days', 'shape_22i'),
    ('trip_23', 'route_23', 'all_days', 'shape_23'),
    ('trip_23d', 'route_23d', 'all_days', 'shape_23d'),
    ('trip_24', 'route_24', 'all_days', 'shape_24'),
    ('trip_25', 'route_25', 'all_days', 'shape_25'),
    ('trip_62b', 'route_62b', 'all_days', 'shape_62b'),
    ('trip_62c', 'route_62c', 'all_days', 'shape_62c')
ON CONFLICT (trip_id) DO NOTHING;

-- Link any existing trip that has no shape yet to its matching shape.
UPDATE trips t SET shape_id = 'shape_' || split_part(t.route_id, '_', 2)
WHERE t.shape_id IS NULL
  AND EXISTS (SELECT 1 FROM route_shapes rs
             WHERE rs.shape_id = 'shape_' || split_part(t.route_id, '_', 2));
